---

- name: packages
  yum: name={{ item }} state=installed
  with_items:
   - mapr-hive
   - mapr-hivemetastore
   - mariadb-server
   - MySQL-python

- name: run the service
  service: name={{ item }} state=started
  with_items:
    - mariadb

- name: create hive user
  mysql_user: name=hive password='{{ hive_password }}' priv=*.*:ALL state=present host={{item}}
  with_items:
    - '%'
    - 'localhost'

- name: create mariadb database
  mysql_db: name=hive state=present

- name: copy hive-site.xml
  copy: src=hive-site.xml dest=/opt/mapr/hive/hive-1.2/conf/hive-site.xml owner=mapr

- name: configure HIVEMETA
  replace:
    dest='/opt/mapr/hive/hive-1.2/conf/hive-site.xml'
    regexp='HIVEMETA'
    replace='{{ hivemeta }}'


- name: restart warden
  service: name={{ item }} state=restarted
  with_items:
    - mapr-warden
