---

- name: set hive_version from mep
  set_fact:
    hive_version : 2.1
  when: mep_version is defined and mep_version == '3.0'

- name: set hive_version from mep
  set_fact:
    hive_version : 1.2
  when: mep_version is not defined

- name: packages
  yum: name={{ item }} state=installed
  with_items:
   - mapr-hive
   - mapr-hivemetastore
   - MySQL-python

- name: copy hive-site.xml
  copy: src=hive-site.xml dest=/opt/mapr/hive/hive-{{ hive_version }}/conf/hive-site.xml owner=mapr

- name: create hive tables if it is not created yet
  shell: if [ `mysql -u hive -phive -h{{ hivemeta }} -e 'use hive; show tables' | wc -l` -ge 10 ] ; then echo "table already created" ; else mysql -u hive -phive hive < /opt/mapr/hive/hive-{{ hive_version }}/scripts/metastore/upgrade/mysql/hive-schema-{{ hive_version }}.0.mysql.sql ; fi
  args:
    chdir:  /opt/mapr/hive/hive-{{ hive_version }}/scripts/metastore/upgrade/mysql/

- name: configure ZOOKEEPER_NODES
  replace:
    dest='/opt/mapr/hive/hive-{{ hive_version }}/conf/hive-site.xml'
    regexp='ZOOKEEPER_NODES'
    replace='{{ zookeeper_nodes }}'

- name: configure HIVEMETA
  replace:
    dest='/opt/mapr/hive/hive-{{ hive_version }}/conf/hive-site.xml'
    regexp='HIVEMETA'
    replace='{{ hivemeta }}'

