---

- name: download epel
  get_url:
    url: http://ftp.jaist.ac.jp/pub/Linux/Fedora/epel//6/x86_64/epel-release-6-8.noarch.rpm
    dest: /tmp

- name: update epel
  yum:
    name: /tmp/epel-release-6-8.noarch.rpm
    state: present

- name: copy mariadb repo file
  copy: src=mariadb.repo dest=/etc/yum.repos.d/mariadb.repo
  when: db == 'mariadb'

- name: install mapr packages
  yum: name={{ item }} state=installed
  with_items:
    - mapr-core
    - mapr-fileserver
    - mapr-zk-internal
    - java-devel
    - clustershell

- name: add JAVA_HOME
  lineinfile:
    dest: '/opt/mapr/conf/env.sh'
    regexp: '^#export JAVA_HOME='
    backrefs: yes
    line: 'export JAVA_HOME=/usr/lib/jvm/jre-1.7.0'
    state: present

- name: copy clustershell group setting template
  copy: src=groups dest=/etc/clustershell/groups

- name: configure clustershell group
  replace:
    dest='/etc/clustershell/groups'
    regexp='CLUSTERSHELLNODES'
    replace='{{ clush_nodes }}'

- name: add core-site.xml
  copy: src=core-site.xml dest=/opt/mapr/hadoop/hadoop-2.7.0/etc/hadoop/core-site.xml owner=mapr

