---

- name: set hive_version from mep
  set_fact:
    hive_version : 2.1
  when: mep_version is defined and mep_version == '3.0'

- name: set hive_version from mep
  set_fact:
    hive_version : 1.2
  when: mep_version is not defined

- name: packages
  yum: name={{ item }} state=installed
  with_items:
   - mapr-hive
   - mapr-hiveserver2

- name: configure ZOOKEEPER_NODES
  replace:
    dest='/opt/mapr/hive/hive-{{ hive_version }}/conf/hive-site.xml'
    regexp='ZOOKEEPER_NODES'
    replace='{{ zookeeper_nodes }}'

- name: configure HIVEMETA
  replace:
    dest='/opt/mapr/hive/hive-{{ hive_version }}/conf/hive-site.xml'
    regexp='HIVEMETA'
    replace='{{ hivemeta }}'

