---

- name: set hive_version from mep
  set_fact:
    hive_version : 2.1
  when: mep_version == '3.0'

- name: packages
  yum: name={{ item }} state=installed
  with_items:
   - mapr-hive
   - mapr-hiveserver2

- name: enable hive impersonation part1
  lineinfile:
    dest=/opt/mapr/hadoop/hadoop-2.7.0/etc/hadoop/core-site.xml
    state=present
    regexp='<!-- hiveimpersonation'
    line=''

- name: enable hive impersonation part2
  lineinfile:
    dest=/opt/mapr/hadoop/hadoop-2.7.0/etc/hadoop/core-site.xml
    state=present
    regexp='hiveimpersonation-->'
    line=''

- name: configure ZOOKEEPER_NODES
  replace:
    dest='/opt/mapr/hive/hive-{{ hive_version }}/conf/hive-site.xml'
    regexp='ZOOKEEPER_NODES'
    replace='{{ zookeeper_nodes }}'

- name: configure HIVEMETA
  replace:
    dest='/opt/mapr/hive/hive-{{ hive_version }}/conf/hive-site.xml'
    regexp='HIVEMETA'
    replace='{{ hivemeta }}'

