---

- name: make dir
  shell: if /usr/bin/hadoop fs -ls /apps | grep -sq spark ; then echo apps dir already created ; else /usr/bin/hadoop fs -mkdir /apps/spark ; fi

- name: change owner of spark dir
  shell: /usr/bin/hadoop fs -chown mapr:mapr /apps/spark

