---

- name: packages
  yum: name=MySQL-python state=installed

- name: packages
  yum: name=mysql-server state=installed
  when: db == 'mysqldb'

- name: packages
  yum: name=mariadb-server state=installed
  when: db == 'mariadb'

- name: run mysql service
  service: name=mysqld state=started enabled=yes
  when: db == 'mysqldb'

- name: run mariadb service
  service: name=mariadb state=started enabled=yes
  when: db == 'mariadb'

- name: create hive user
  mysql_user: name=hive password='{{ hive_password }}' priv=*.*:ALL state=present host={{item}}
  with_items:
    - '%'
    - 'localhost'
    - '{{ hivemeta }}'
  when: hive_password is defined

- name: create hue user
  mysql_user: name=hue password='{{ hue_password }}' priv=*.*:ALL state=present host={{item}}
  with_items:
    - '%'
    - 'localhost'
    - '{{ hivemeta }}'
  when: hue_password is defined
  
- name: create hive database
  mysql_db: name=hive state=present
  when: hive_password is defined

- name: create hue database
  mysql_db: name=hue state=present
  when: hue_password is defined

