---

- name: configure.sh
  shell: /opt/mapr/server/configure.sh -C '{{ cldb_nodes }}' -Z '{{ zookeeper_nodes }}' -N '{{ cluster_name }}'

- name: configure.sh with resource manager and history server
  shell: /opt/mapr/server/configure.sh -C '{{ cldb_nodes }}' -Z '{{ zookeeper_nodes }}' -HS '{{ historyserver }}' -N '{{ cluster_name }}'
  when: resource_manager is defined and historyserver is defined

- name: configure.sh with resource manager, history server, and spyglass
  shell: /opt/mapr/server/configure.sh -C '{{ cldb_nodes }}' -Z '{{ zookeeper_nodes }}' -HS '{{ historyserver }}' -N '{{ cluster_name }}' -ES '{{ elastic_search }}' -OT '{{ opentsdb }}'
  when: resource_manager is defined and historyserver is defined and elastic_search is defined and opentsdb is defined

