---

# This command copy your public key in $HOME/.ssh/id_rsa.pub to remote nodes.
# Uncomment if you want to do this
#- name: Set authorized key for user root copying it from current user
#  authorized_key:
#    user: root
#    state: present
#    key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"

- name: packages
  yum: name={{ item }} state=installed
  with_items:
   - zsh
   - vim
   - lsof
   - wget
   - ntp
   - curl
   - device-mapper
   - iputils
   - libsysfs
   - lvm2
   - nc
   - nfs-utils
   - nss
   - ntp
   - openssh-clients
   - openssh-server
   - openssl
   - python-devel
   - python-pycurl
   - sdparm
   - sshpass
   - sudo
   - syslinux
   - sysstat
   - wget
   - which

- name: run ntp service
  service: name={{ item }} state=started enabled=yes
  with_items:
    - ntpd

- name: copy rcfiles
  copy: src=.zshrc dest=/root/.zshrc

- name: copy /etc/hosts
  copy: src=hosts dest=/etc/hosts
  when: use_hosts == 'yes'

- name: create mapr, dev, mkt group
  group:
    name: "{{ item.name }}"
    state: present
    gid: "{{ item.gid }}"
  with_items:
    - { name: 'mapr', gid: '5000' }
    - { name: 'mkt',  gid: '6000' }
    - { name: 'dev',  gid: '7000' }

- name: add mapr, mark, sharon user
  user:
    name:     "{{ item.name }}"
    uid:      "{{ item.uid }}"
    group:    "{{ item.group }}"
    password: "{{ item.password }}"
  with_items:
    - { name: 'mapr',     uid: '5000', group: 'mapr', password: '$6$0FsX6QWhxP5yHf0.$ceGG6Crjyjnwc9MHsgvPEakdNS.Q76VvDFb4k2l6KGNYjdGzFTG5yxq6bPUsBBuhpw/i.e50aeH1.RYJDGKaJ0' }
    - { name: 'mark',     uid: '700',  group: 'dev',  password: '$6$zfbXJCZmmJXzhoFf$1dx6kN5dg1luO4lFpAwCHl1thuznwtTOlMvkC72EqL.ux67DOtWjCU79MAzMjWtnJta9m8kwqtSryMfN56F1U1' }
    - { name: 'user01',   uid: '701',  group: 'dev',  password: '$6$EeFZrsT6n1OJcuWB$479VWcEIf.uPX4tMPGIdHfuujyvvQ7nxm9TJwcCSu5YavXHS3y.WlJqmku1GHeqM8eA8oNktimbT.zpcNnm7v/' }
    - { name: 'sharon',   uid: '600',  group: 'mkt',  password: '$6$toCIj6aS9K73k3vn$RrrYN6zchyzgCu1t6lFH1qSKCl6s81bANLsiv4jAiZlDMymsaewaXkV7/2n/KA92vuSmYuHLCig0q40MGTSx11' }

- name: import rpm key
  rpm_key:
    state: present
    key: http://package.mapr.com/releases/pub/maprgpg.key

- name: copy repo file
  copy: src=maprtech.repo dest=/etc/yum.repos.d/maprtech.repo

- name: set mapr version
  replace:
    dest='/etc/yum.repos.d/maprtech.repo'
    regexp='MAPR_VERSION'
    replace='{{ mapr_version }}'

- name: set MEP version
  replace:
    dest='/etc/yum.repos.d/maprtech.repo'
    regexp='MEP_VERSION'
    replace='{{ mep_version }}'
