---

- name: packages
  yum: name={{ item }} state=installed
  with_items:
   - zsh
   - vim
   - lsof
   - wget
   - ntp

- name: run ntp service
  service: name={{ item }} state=started enabled=yes
  with_items:
    - ntpd

- name: copy rcfiles
  copy: src=.zshrc dest=/root/.zshrc

- name: copy /etc/hosts
  copy: src=hosts dest=/etc/hosts
  when: use_hosts == 'yes'

- name: mapr group
  group:
    name: mapr
    state: present
    gid: 5000

- name: mapr user
  user:
    name: mapr
    uid: 5000
    group: mapr
    password: '{{ mapruser_password }}'

- name: import rpm key
  rpm_key:
    state: present
    key: http://package.mapr.com/releases/pub/maprgpg.key

- name: copy repo file
  copy: src=maprtech.repo dest=/etc/yum.repos.d/maprtech.repo

- name: set mapr version
  replace:
    dest='/etc/yum.repos.d/maprtech.repo'
    regexp='MAPR_VERSION'
    replace='{{ mapr_version }}'

- name: set MEP version
  replace:
    dest='/etc/yum.repos.d/maprtech.repo'
    regexp='MEP_VERSION'
    replace='{{ mep_version }}'
